# Generated by Django 4.2.7 on 2023-11-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='edited',
        ),
    ]
